name: Prepare Source of Diary

on:
  workflow_run:
    workflows: [Push File from Shortcut]
    types:
      - completed
  push:
    paths:
        - '**/diary.md'

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 2
    
      - name: Check Files
        run: |
          TARGETS=$(git diff --name-only --diff-filter=ACMR HEAD~1 HEAD -- '**/diary.md')

          echo "=== Detected Target Files ==="
          if [ -z "${TARGETS}" ]; then
            echo "No matching changed files found."
            exit 0
          else
            echo "${TARGETS}"
          fi
          echo "============================="

          printf "TARGETS<<EOF\n%s\nEOF\n" "${TARGETS}" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      - name: Run Script for Each File
        run: |
          if [ -z "${TARGETS}" ]; then
            echo "No target files to process."
            exit 0
          fi

          echo "${TARGETS}" | while IFS= read -r file; do
            [ -z "$file" ] && continue

            echo "=== Executing: resources/scripts/convert-diary.py $file ==="
            python resources/scripts/convert-diary.py "$file"
          done

      - name: Git Push
        run: |
          git config --local user.email "github-actions[bot]@://github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          if ! git diff --cached --exit-code --quiet; then
            git commit -m "Prepare source.md via GitHub Actions"
            git push
          else
            echo "No changes detected. Skipping commit."
          fi
